### ISSUE TITLE
Bizzare error with DDE system

### ISSUE THREAD

**Issue by adhalanay** [JuliaDiffEq/DelayDiffEq.jl#168]
I don't know if this the right venue to report this. If there is a better place please let me know and close the issue. Here is my problem:

 I have the system of delay-differential equations implemented [here](https://gist.github.com/adhalanay/5cf1d44448d3fe6deb903d048008ca78), more precisely in the function `all_model`.
 When I try to run this code it fails with 

`ERROR: BoundsError: attempt to access 1-element Array{Float64,1} at index [2]`

If it is of any interest here is also the [stacktrace](https://gist.github.com/adhalanay/4546ba2be5f3a177439b58d01e8c8f98).

The error appears only when `h0(p,t)[1]=0`.

**Comment by devmotion** [comment]
Thanks for reporting the issue! I can reproduce your problem and actually on master (that's the latest release) of DelayDiffEq I observe the same errors when running the CI tests.

The problem seems to be caused by recent changes of the interpolation handling in OrdinaryDiffEq, more concretely by one of [the commits between 5.27.0 and 5.27.1](https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/compare/v5.27.0...v5.27.1). With OrdinaryDiffEq 5.27.0 the test failures on master disappear and I can solve your DDE system even if `h0(p, t)[1] = 0`.

So until there's a new version of OrdinaryDiffEq in which this bug is fixed, you can work around this problem by downgrading OrdinaryDiffEq to version 5.27.0. I hope that helps!

**Comment by adhalanay** [comment]
I can confirm that the bug is gone. Thank you for your very prompt fix!
