### ISSUE TITLE
reeval_internals should fix `uprev` and `uprev2` as well

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DelayDiffEq.jl#46]
https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/master/src/callbacks.jl#L27

**Comment by devmotion** [comment]
You mean `uprev` and `uprev2` of the ODE integrator, I guess, since the DDE integrator only needs an update of its interpolation data `k`, similar to 
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/integrator_interface.jl#L22-L28
in OrdinaryDiffEq? These updates of `t`, `dt`, and `u` of the ODE integrator in `reeval_internals_due_to_modification!` are only to make sure that the ODE integrator (responsible for interpolation) does not interpolate on an interval that goes beyond the newly set time `t` of the DDE integrator with a different `u`. But `uprev` of the ODE integrator is always just updated to the final state of the solution in
https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/master/src/integrator_utils.jl#L272-L273
and if the step fails reset to the state vector of the last integration step from the solution in
https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/master/src/integrator_interface.jl#L89-L93
together with `tprev`.
Moreover, `uprev` is never copied from the solution to the ODE integrator since it is never written to - it is only used for interpolation. Finally, `uprev2` of the ODE integrator is never updated in the whole algorithm so far. I assumed for interpolation `uprev2` is not needed. Am I wrong? Otherwise there is no use in updating `uprev2` only in `reeval_internals_due_to_modification!`.

**Comment by ChrisRackauckas** [comment]
Oh no, that sounds right. I was just marking this because I saw it was missing while working on the initialization. I was thinking that after a discontinuity, `uprev` and `uprev2` would need to be handled. But doesn't make sense to use them if there was just a discontinuity, so I forgot for a second that what happens instead is the ODEIntegrator sets the booleans so that way `perform_step!` and all other functions know to not use the history, and it corrects itself from there. My mistake.
